import GameCard from "@/components/GameCard";
import GpuCard from "@/components/GpuCard";
import DeviceCard from "@/components/DeviceCard";
import BenchmarkTable from "@/components/BenchmarkTable";
import Breadcrumb from "@/components/Breadcrumb";
import UpgradeAdviceCard from "@/components/UpgradeAdviceCard";
import { games,gpus,cpus,devices,blogPosts,findGame,findGpu,findDevice,findPost,benchmarks } from "@/lib/data";
import { classifyGame } from "@/lib/compatibility-engine";
import { getBenchmarkTable, getCompatibleDevices, getRecommendedConfigs } from "@/lib/reverse-lookup";
import { formatVnd, priceRangeLabel } from "@/lib/utils";
export default function Home(){ const gameRows=games.slice(0,8); return <div><section className="bg-blue-700 py-14 text-white"><div className="container"><h1 className="text-4xl font-black">Máy Này Chơi Được Game Gì?</h1><p className="mt-4 max-w-2xl">Nhập CPU, GPU, RAM và độ phân giải để xem game chơi được, FPS ước tính và thiết bị phù hợp.</p><a className="btn mt-6 bg-white text-blue-700" href="/tra-cuu">Kiểm tra ngay</a></div></section><section className="container py-10"><form action="/tra-cuu" className="card grid gap-3 p-4 md:grid-cols-5"><select name="gpu" className="input">{gpus.slice(0,20).map(g=><option key={g.slug} value={g.slug}>{g.name}</option>)}</select><select name="cpu" className="input">{cpus.slice(0,20).map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select><select name="ram" className="input"><option value="8">8GB RAM</option><option value="16">16GB RAM</option></select><select name="res" className="input"><option value="1080p">1080p</option><option value="720p">720p</option></select><button className="btn">Kiểm tra cấu hình</button></form><h2 className="mt-10 text-2xl font-black">Game phổ biến</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{gameRows.map(g=><GameCard key={g.slug} game={g}/>)}</div><h2 className="mt-10 text-2xl font-black">GPU phổ biến tại Việt Nam</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{gpus.slice(0,6).map(g=><GpuCard key={g.slug} gpu={g} count={games.length}/>)}</div><h2 className="mt-10 text-2xl font-black">Laptop gaming theo tầm giá</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{devices.slice(0,6).map(d=><DeviceCard key={d.slug} device={d}/>)}</div><h2 className="mt-10 text-2xl font-black">Bài viết mới nhất</h2><div className="mt-4 grid gap-4 md:grid-cols-4">{blogPosts.slice(0,4).map(p=><a className="card p-4 font-bold" key={p.slug} href={"/blog/"+p.slug}>{p.title}</a>)}</div><h2 className="mt-10 text-2xl font-black">Tìm game theo nhu cầu</h2><div className="mt-4 flex flex-wrap gap-2">{["Game miễn phí","Game nhẹ dưới 5GB","Game offline","Game co-op","Game cho máy yếu"].map(x=><a className="rounded-md border px-3 py-2" key={x} href="/chon-game">{x}</a>)}</div></section></div> }
