import gamesData from "@/data/games.json";
import gpusData from "@/data/gpus.json";
import cpusData from "@/data/cpus.json";
import devicesData from "@/data/devices.json";
import benchmarksData from "@/data/benchmarks.json";
import blogData from "@/data/blog-posts.json";
import gameImagesData from "@/data/game-images.json";
import type { Benchmark, BlogPost, Cpu, Device, Game, Gpu } from "@/types";
export const games = gamesData as unknown as Game[];
export const gpus = gpusData as unknown as Gpu[];
export const cpus = cpusData as unknown as Cpu[];
export const devices = devicesData as unknown as Device[];
export const benchmarks = benchmarksData as unknown as Benchmark[];
export const blogPosts = blogData as unknown as BlogPost[];
export const gameImages = gameImagesData as Record<string, string[]>;
export const findGame = (slug: string) => games.find((x) => x.slug === slug);
export const findGpu = (slug: string) => gpus.find((x) => x.slug === slug);
export const findCpu = (slug: string) => cpus.find((x) => x.slug === slug);
export const findDevice = (slug: string) => devices.find((x) => x.slug === slug);
export const findPost = (slug: string) => blogPosts.find((x) => x.slug === slug);
