import GameCard from "@/components/GameCard";
import GpuCard from "@/components/GpuCard";
import DeviceCard from "@/components/DeviceCard";
import BenchmarkTable from "@/components/BenchmarkTable";
import Breadcrumb from "@/components/Breadcrumb";
import UpgradeAdviceCard from "@/components/UpgradeAdviceCard";
import { games,gpus,cpus,devices,blogPosts,findGame,findGpu,findDevice,findPost,benchmarks } from "@/lib/data";
import { classifyGame } from "@/lib/compatibility-engine";
import { getBenchmarkTable, getCompatibleDevices, getRecommendedConfigs } from "@/lib/reverse-lookup";
import { formatVnd, priceRangeLabel } from "@/lib/utils";
export const revalidate=86400; export function generateStaticParams(){return games.map(game=>({gameSlug:game.slug}))} export async function generateMetadata({params}:{params:Promise<{gameSlug:string}>}){const {gameSlug}=await params; const game=findGame(gameSlug); return {title: game? game.name+" - Cấu hình tối thiểu, FPS benchmark, thiết bị đề xuất":"Không tìm thấy game", description: game? game.description:"Game không tồn tại"} } export default async function GameDetail({params}:{params:Promise<{gameSlug:string}>}){ const {gameSlug}=await params; const game=findGame(gameSlug); if(!game) return <section className="container py-8"><h1>Không tìm thấy game</h1></section>; const table=getBenchmarkTable(game.slug); return <section className="container py-8"><Breadcrumb items={[{href:"/",label:"Trang chủ"},{href:"/chon-game",label:"Chọn game"},{href:"#",label:game.name}]}/><h1 className="text-3xl font-black">{game.name}</h1><p className="mt-3 max-w-3xl">{game.description}</p><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="card p-4"><h2 className="font-bold">Cấu hình tối thiểu</h2><p>CPU: {game.minSpecs.cpuName}</p><p>GPU: {game.minSpecs.gpuName}</p><p>RAM: {game.minSpecs.ramGb}GB</p></div><div className="card p-4"><h2 className="font-bold">Cấu hình đề xuất</h2><p>CPU: {game.recSpecs.cpuName}</p><p>GPU: {game.recSpecs.gpuName}</p><p>RAM: {game.recSpecs.ramGb}GB</p></div></div><h2 className="mt-8 text-2xl font-black">Đề xuất thiết bị theo tầm giá</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{getCompatibleDevices(game.slug).slice(0,6).map(d=><DeviceCard key={d.slug} device={d}/>)}</div><h2 className="mt-8 text-2xl font-black">Bảng benchmark FPS</h2><BenchmarkTable rows={table.slice(0,80)}/><h2 className="mt-8 text-2xl font-black">Video test hiệu năng</h2><div className="mt-3 grid gap-2">{table.slice(0,6).map(v=><a className="text-blue-600" key={v.gpuSlug+v.resolution} href={v.videoTestUrl??"#"} target="_blank" rel="nofollow">Video test {v.gpuSlug} {v.resolution}</a>)}</div></section> }
